### ISSUE TITLE
Can not see content when public

### ISSUE THREAD

**Issue by craigvu** [ist-dresden/composum-nodes#221]
I try to public a site in composum platform but can not see the content if I do not login 
It display https://i.stack.imgur.com/3mb9o.png

**Comment by ist-rw** [comment]
It seems that the required permissions are missing for anonymous access. Normally, access for 'everyone' is severely restricted. But the Platform module comes with an ACL setup script to set up the ACLs necessary for public access to the Platform functions.

/conf/composum/platform/security/acl/everyone.json

However, this script is not automatically executed when the Platform module is installed.

I have therefore added a new view in Composum Nodes that allows manual execution of ACL setup JSON files in the browser. This feature has been made generally available with the current release Composum Nodes 2.2.1.

[https://www.composum.com/home/nodes/aclsetup.html](https://www.composum.com/home/nodes/aclsetup.html)

The same applies to the Pages resources. Here, too, anonymous access is initially not allowed. Therefore, rules would have to be added for direct delivery from /content. However, there is currently no suitable preconfigured script for this.

I would recommend the inplace replication instead of the direct access to '/content/...' for the delivery of the published content. Then a simple 'grant "jcr:read"' rule for 'everyone' at the '/public' path is sufficient to allow public access.

**Comment by craigvu** [comment]
Thank you for your answer, I will follow your guidance later.

**Comment by stoerr** [comment]
Since that's rather old and hopefully answered, I'd like to close this issue.
