### ISSUE TITLE
Composum settings and bundle page does not work in the cloud

### ISSUE THREAD

**Issue by royteeuwen** [ist-dresden/composum-nodes#289]

**Comment by royteeuwen** [comment]
Fixed by: https://github.com/ist-dresden/composum-nodes/pull/288

**Comment by stoerr** [comment]
Thank you for your contribution! I currently can't try that out on a AEMaaCS system, but since the PR was merged into the Nodes 4.x version and it's in release 4.1.3, I'm closing this. Please feel free to contact us if there are more problems! I guess the composum Browser is a pretty valuable tool for AEMaaCS, since there are quite some things missing there.

**Comment by royteeuwen** [comment]
It definitely is @stoerr ;)! So thanks for the work.
