### ISSUE TITLE
Composum Nodes now requires Guava

### ISSUE THREAD

**Issue by rombert** [ist-dresden/composum-nodes#323]
Hi,

I tried to update the Sling Starter to use the latest 4.3.0 version Composum Nodes but got this error instead

> [ERROR] [bundle-packages] com.composum.nodes:composum-nodes-console:4.3.0: Bundle is importing package com.google.common.collect with start order 20 but no bundle is exporting these for that start order.

We have stopped using Guava in the Sling Starter since the versioning story is quite complicated and makes upgrading very difficult.

Could this dependency on Guava be removed or made optional?

**Comment by rombert** [comment]
Sounds good, thanks @stoerr !

**Comment by stoerr** [comment]
@rombert : Done: the release https://github.com/ist-dresden/composum-nodes/releases/tag/composum-nodes-4.3.1 removes guava and includes some nice features as well. :-)

**Comment by rombert** [comment]
Thanks @stoerr ! I've updated the Sling Starter to the latest version just now. The OpenAI part looks interesting, does it bring good results in your experience?

**Comment by stoerr** [comment]
@rombert Thank you! Well, gpt-3.5-turbo isn't really good enough for that, but I've been trying that with gpt-4-turbo-preview and the results usually worked nicely. So if none of the templates match, that is certainly worth a shot for queries you can't write from the top of your head.

I guess I should add Anthropic's Claude as a second backend option, though, because you can currently get free evaluation access to even their best model, while I've just noticed there are even some hurdles to get to OpenAI's gpt-4 even for a paying new customer. :-/ But all in all yes, I think it is worth it.

Did you try AI some LLM stuff yourself? I'm all over that for quite a while now, doing https://ist-dresden.github.io/composum-AI/ and quite a couple of sparetime projects https://www.stoerr.net/ai in the last year. That's so much fun and such a speed up. :-) It moved the amount and level of stuff I can do quite a lot upward, because writing code is just so much easier and quicker.

**Comment by rombert** [comment]
I did not do too much with GenAI so far, I am trying to figure out where it is applicable. And seeing both productive and spare-time projects is very useful.

One thing which you could consider is making the OpenAI API endpoint configurable. It is possible to run different LLMs using Ollama and expose an OpenAI-compatible REST API - https://github.com/ollama/ollama/blob/main/docs/openai.md . Having it configurable in Composum would make it possible to use local LLMs. Of course, there is no guaratee that the results are comparable with GPT-4, but at least it's a start :-)

**Comment by stoerr** [comment]
Right. I tried a little with LM Studio but the queries that came out of the models I tried weren't exactly useful. No surprise there, as even GPT-3.5 is not quite good enough. :-) But I'll put that in, and at least Claude would certainly be a suitable option.

Well, if you don't have that already, I'd very much suggest getting Github Copilot or something similar. I cannot really put numbers on it, but it feels like depending on what you're doing that can easily double your coding speed. And there is a nice ChatGPT like chat that can also improve the thinking time once in a while.
