### ISSUE TITLE
Package Manager response in JSon

### ISSUE THREAD

**Issue by schaefa** [ist-dresden/composum-nodes#70]
As of now the PackageServlet Service Command's response is in HTML as expected from /bin/cpm/package.service.html.

That said for a better handling in a programmatic invocation (see https://wcm-io.atlassian.net/browse/WTOOL-29) it would be better if the response could be returned in JSon. The URL could be changed then to /bin/cpm/package.service.json).

- Andy

**Comment by schaefa** [comment]
After going through the code I discovered that you provide upload, install etc with JSon response and that is more what I was looking for.

I would prefer to have some documentation about the API but for now I start to understand the code and can piece it together myself.

**Comment by stoerr** [comment]
Nice to hear that you found something to use! As long as there isn't much public demand: that API isn't primarily meant as a public API and could change sometimes when we add new functionality. So we  prefer just to use the code as documentation, since the code is public. So I'd like to close this issue.
